config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :sweats, only: [:edit, :update, :show]
  resources :profile
  
  authenticated do
    root :to => 'sales#index', as: :authenticated
  end

  root :to => 'welcome#index'

  get 'buy' => 'sales#buy'
  get 'sell' => 'sweats#show'
  

end

app/models/offer.rb
class Offer < ActiveRecord::Base

	# @offer = Offer.first
	# Remember that @offer.seller returns a Sweat class, to get the profile associated with it:
	# @offer.seller.profile
	
	belongs_to :seller , :class_name => "Sweat", :foreign_key => "sweat_id"
	belongs_to :buyer, :class_name => "Profile", :foreign_key => "profile_id"

	after_create :set_initial_state

	STATES = %w{ pending accepted complete canceled }

	STATES.each do |state|
		define_method("#{state}?") do
			self.state == state
		end

		define_method("#{state}!") do
			self.update_attribute(:state, state)
		end
	end

	private
		def set_initial_state
			self.update_attribute(:state, "pending")
		end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_one :sweat

	has_many :offers

	before_create :build_default_sweat
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "150x150>" }
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/




	def build_default_sweat
		build_sweat
		true
	end

end

app/models/sweat.rb
class Sweat < ActiveRecord::Base
	belongs_to :profile
	has_many :offers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :avatar_name
  validates_uniqueness_of :avatar_name
  before_create :build_default_profile


  has_one :profile
  has_one :sweat, through: :profile


  def build_default_profile
  	build_profile
  	true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_last_seen_at, if: proc { user_signed_in? && (session[:last_seen_at] == nil || session[:last_seen_at] < 15.minutes.ago) }
  
  
  private
	  def set_last_seen_at
	  	current_user.profile.update_attribute(:last_seen_at, Time.now)
	  	session[:last_seen_at] = Time.now
	  end  


  protected
	  def configure_permitted_parameters
	    devise_parameter_sanitizer.for(:sign_up) << :avatar_name
	    devise_parameter_sanitizer.for(:account_update) << :avatar_name
	  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

	def create
		@offer = Offer.new(offer_params)
		if @offer.save
			
			Notification.create(recipient_id: @offer.seller.profile.id, 
													sender_id: @offer.buyer.id, 
													offer_id: @offer.id, 
													notification_type: "new_offer")

			redirect_to @offer.seller.profile
			flash[:alert] = "Offer successfully created"
		else
			render 'new'
		end
	end

	private
		def offer_params
			params.require(:offer).permit(:amount, :profile_id, :sweat_id)
		end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_filter :authenticate_user!, only: [:edit, :update]

	def show
		@profile = Profile.find(params[:id])

		if @profile == current_user.profile
			@pending_offers = @profile.offers.where(state: "pending")
			@accepted_offers = @profile.offers.where(state:"accepted")
			@completed_offers = @profile.offers.where(state:"complete")
			@canceled_offers = @profile.offers.where(state:"canceled")

			@pending_sales = @profile.sweat.offers.where(state:"pending")
			@accepted_sales = @profile.sweat.offers.where(state:"accepted")
			@completed_sales = @profile.sweat.offers.where(state:"complete")
			@canceled_sales = @profile.sweat.offers.where(state:"canceled")
		end

		

		respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user }
    end
	end

	def edit
		@profile = current_user.profile
	end



	def update
		@profile = current_user.profile
		if @profile.update_attributes(profile_params)
			flash[:info] = "Profile Updated"
			redirect_to @profile
		end
	end

	private
		def profile_params
			params.require(:profile).permit(:bio, :avatar)
		end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

	def index
	end

	def buy
		@sweat = Sweat.all
	end
end

app/controllers/sweats_controller.rb
class SweatsController < ApplicationController
	before_filter :authenticate_user!

	def show
		@sweat = current_user.sweat
		@offers = @sweat.offers
	end

	def edit
		@sweat = current_user.sweat
	end

	def update
		@sweat = current_user.sweat
		if @sweat.update_attributes(sweat_params)
			flash[:info] = "Sweat Shop Updated"
			redirect_to sell_path
		end
	end

	private
		def sweat_params
			params.require(:sweat).permit(:amount)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sweats_helper.rb
module SweatsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Entropiasweat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Sweatropia</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "Dashboard", current_user.profile %></li>
            <li><%= link_to "Buy", buy_path %></li>
            <li><%= link_to "Sell", sell_path %></li>
          <li><%= link_to 'Sign out', '/users/sign_out', :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Register', new_user_registration_path %></li>
          <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name}")%>
    <% end %>

  <%= yield %>
</body>
</html>

app/views/sales/buy.html.erb
<p>Buy Sweat here!</p>

<ul class="all-sweat">
  <% @sweat.each do |sweat| %>
    <li>
    	<%= sweat.amount %>
      <%= sweat.profile.user.avatar_name %>
    </li>
  <% end %>
</ul>

app/views/sales/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			<div id="Sweat-icon-large"></div>
		</div>
	</div> 

	<div class="row">
		<div class="col-sm-3 col-sm-offset-2">
			<%=link_to buy_path, class: "btn btn-lg btn-default", id: "Buy-icon" do%>
		  	<h1>Buy</h1>
			<%end%>
		</div>

		<div class="col-sm-3 col-sm-offset-2">
			<%=link_to sell_path, class: "btn btn-lg btn-default", id: "Sell-icon" do %>
		  	<h1>Sell</h1>
			<%end%>
		</div>

	</div>
</div>

app/views/sweats/edit.html.erb
<%= form_for(@sweat) do |f| %>
	<div class="container">
		<div class="row">
			<div class= "col-md-8 col-md-offset-2">

				<div class="panel panel-default">
					<div class="panel-body">
						<div class="form-inputs">
						  <div class="form-group">
						    <%= f.label :amount %><br />
						    <%= f.number_field :amount, autofocus: true %>
						  </div>
						</div>
					</div>
					<div class="panel-footer">
						<%= button_to "Update", sweat_path(current_user.sweat), data: { confirm: "Are you sure?" }, method: :put, class: "btn btn-primary" %>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>
  

app/views/sweats/show.html.erb
<h1><%= current_user.avatar_name %></h1>
<p>Sweat available: <%= @sweat.amount %></p>
<p>Price: <%= @sweat.price %> </p>

Your offers:
  <% @offers.each do |offer| %>
    <li>
    	Buyer: <%= offer.buyer.user.avatar_name %>
      | Amount wanted: <%= offer.amount %>
    </li>
 	<% end %>

<%= link_to "Update", edit_sweat_path(current_user.sweat), html_options= {class: "btn btn-primary"} %>

app/views/users/show.html.erb
<h1><%= @user.avatar_name %></h1>

app/views/welcome/index.html.erb
<div class="jumbotron text-center">

	<h1>Welcome to Sweatropia</h1>
	<h3>Entropia's premier destination for buying and selling sweat<h3>

	<div class="btn-group">
		<%=link_to "Sign up", new_user_registration_path, :class => "btn btn-primary btn-lg"%>
		<%=link_to "Sign in", new_user_session_path, :class => "btn btn-default btn-lg"%>
	</div>

</div>

<div class="container-fluid">
	<div class="col-lg-10 col-lg-offset-1">
			<div class="row">
				<div class="col-lg-2">
					<div id="how-picture-1"></div>
				</div>
				<div class="col-lg-10">
					<h1>Do this thing</h1>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-2 col-lg-push-10">
					<div id="how-picture-2"></div>
				</div>
				<div class="col-lg-10 col-lg-pull-2">
					<h1>Do this thing</h1>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-2">
					<div id="how-picture-3"></div>
				</div>
				<div class="col-lg-10">
					<h1>Do this thing</h1>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
				</div>
			</div>

	</div>
</div>